In [2]:
import pandas as pd
import sqlite3

cnx = sqlite3.connect('dolphyn_results.db')

df1 = pd.read_sql_query("SELECT * FROM HSC_storage", cnx)
df1.head()

,timesteps,Small_Electrolyzer_1,Small_Electrolyzer_2,Small_Electrolyzer_3,Flex_Demand_1,Large_SMR_1,Large_SMR_2,Large_SMR_3,Large_SMR_wCCS_90pct_1,Large_SMR_wCCS_90pct_2,Large_SMR_wCCS_90pct_3,Above_ground_storage_1,Above_ground_storage_2,Above_ground_storage_3
0,t1,0.0,0.0,0.0,4.000,0.0,0.0,0.0,0.0,0.0,0.0,106.825554,566.766809,244.038923
1,t2,0.0,0.0,0.0,0.400,0.0,0.0,0.0,0.0,0.0,0.0,115.976067,640.527843,274.316006
2,t3,0.0,0.0,0.0,-4.874,0.0,0.0,0.0,0.0,0.0,0.0,125.126579,714.288877,304.593089
3,t4,0.0,0.0,0.0,-4.000,0.0,0.0,0.0,0.0,0.0,0.0,134.277091,781.523910,327.516964
4,t5,0.0,0.0,0.0,-4.000,0.0,0.0,0.0,0.0,0.0,0.0,142.978530,822.934944,343.644048